name: test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17"
      - name: Build native
        run: go build -v ./...
        shell: bash
      - name: Run unit tests
        run: go test -v -race -bench=. ./...
        shell: bash
